### ISSUE TITLE
Publish Model set up documentation

### ISSUE THREAD

**Issue by cedricth** [ow2/riscoss-platform#3]
And publish the KPA Risk Analysis Tool Setup Manual 14 1 2015
https://www.dropbox.com/sh/aonadrvbgi9lffd/AABpe3BrPguHV6l9VlNbHCZ-a?dl=0

**Comment by cjdelisle** [comment]
http://riscoss.projects.ow2.org/xwiki/bin/download/WP4/WebHome/KPARiskAnalysisToolSetupManual1412015.docx
new version

**Comment by cjdelisle** [comment]
done
